fix(config): get errors about conflicts between `ESModule` and `CommonJS`
Error:
- Running command: node sync-dependencies.js
(node:35167) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/beatrizsmerino/Sites/localhost/nuxt-course/sync-dependencies.js:1
import fs from "fs";
^^^^^^
SyntaxError: Cannot use import statement outside a module
- Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/beatrizsmerino/Sites/localhost/nuxt-course/.eslintrc.js from /Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
.eslintrc.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename .eslintrc.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/beatrizsmerino/Sites/localhost/nuxt-course/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
- Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/beatrizsmerino/Sites/localhost/nuxt-course/.eslintrc.js from /Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of .eslintrc.js in /Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
    at module.exports [as default] (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2583:47)
    at loadConfigFile (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2667:20)
    at ConfigArrayFactory.loadInDirectory (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2877:34)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3792:18)
- Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/beatrizsmerino/Sites/localhost/nuxt-course/stylelint.config.js from /Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/cosmiconfig/dist/loaders.js not supported.
stylelint.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename stylelint.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/beatrizsmerino/Sites/localhost/nuxt-course/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
- Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/beatrizsmerino/Sites/localhost/nuxt-course/commitlint.config.js from /Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/cosmiconfig/dist/loaders.js not supported.
commitlint.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename commitlint.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/beatrizsmerino/Sites/localhost/nuxt-course/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
- ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/beatrizsmerino/Sites/localhost/nuxt-course/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/beatrizsmerino/Sites/localhost/nuxt-course/jest.config.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async requireOrImportModule (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/jest-util/build/requireOrImportModule.js:55:32)
    at async readConfigFileAndSetRootDir (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:112:22)
    at async readInitialOptions (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/jest-config/build/index.js:403:13)
    at async readConfig (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/jest-config/build/index.js:147:48)
    at async readConfigs (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/jest-config/build/index.js:424:26)
    at async runCLI (/Users/beatrizsmerino/Sites/localhost/nuxt-course/node_modules/@jest/core/build/cli/index.js:151:59)

Solution:
- Use `"type": "module"` in the `package.json` files.
Use `cjs` extension.