BUGFIX. Get errors about `postcss` when run the `npm run dev` command
Errors:
- The following errors are obtained:
ERROR  Failed to compile with 1 errors
ERROR  in ./layouts/default.vue?vue&type=style&index=0&id=314f53c6&lang=scss&
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Can't resolve '~/assets/scss/components/components-form' in '/Applications/MAMP/htdocs/nuxt-exercises/layouts'
- Stylelint has formatted the code by changing the styles in the way it imports files using `url()`, which breaks the code when postcss compiles.

Solution:
- It is necessary to install the `postcss-import` package and add it to the `postcss` configuration in the `nuxt.config.js` file.
So `postcss` can build and can access the folder and files in `assets/scss`.
- Add and disable the `import-notation` rule of the `stylelint` configuration in the `stylelint.config.js` file.
So it can use `@import` as `string` and as `url`.

References:
- https://www.npmjs.com/package/postcss-import
- https://stackoverflow.com/questions/55262921/how-to-get-postcss-config-working-with-nuxt
- https://github.com/stylelint/stylelint/issues/4055
- https://stylelint.io/user-guide/rules/import-notation/