fix(config): during deploy does not find the `functions/mixins/repo-mixins.js` file
Error:
- Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/beatrizsmerino/Sites/localhost/nuxt-course/functions/mixins/repo-mixins.js' imported from /Users/beatrizsmerino/Sites/localhost/nuxt-course/functions/nuxt.config.js
at finalizeResolution (node:internal/modules/esm/resolve:264:11)
at moduleResolve (node:internal/modules/esm/resolve:917:10)
at defaultResolve (node:internal/modules/esm/resolve:1130:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
at link (node:internal/modules/esm/module_job:84:36) {
code: 'ERR_MODULE_NOT_FOUND',
url: 'file:///Users/beatrizsmerino/Sites/localhost/nuxt-course/functions/mixins/repo-mixins.js'
- /Users/beatrizsmerino/Sites/localhost/nuxt-course/mixins/repo-mixins.js
1:34  error  Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): "importAttributes", "importAssertions". (1:34)

Reason:
- When deploying with the `firebase deploy --only functions` command, it does not find the relative path `./mixins/repo-mixins.js`, used in the `nuxt.config.js` file. This is because the `nuxt.config.js` file is copied during deployment to the `functions` folder and inside it, the `mixins` folder does not exist.

Solution:
- A js script has been created, which will be executed with a command before the deploy. It will get from the `./mixins/repo-mixins.js` file, the name and description of the repository of the `package.json` file, and with that data it will create environment variables. The environment variables can be used in the `nuxt.config.js` file, in the components and in the pages, obtaining the information as before.

Steps:
- Create in the root of the project the `env-package.js` file.
In the `nuxt.config.js` file, `PageHeader` component and `about` page, do not import the `./mixins/repo-mixins.js` file, import it inside `env-package.js`.
In the `env-package.js` file, the `./mixins/repo-mixins.js` file uses the `getRepoName` and `getRepoDescription` functions for the same purpose as before, only this time it stores the returned values in `PACKAGE__NAME` and `PACKAGE__DESCRIPTION` variables in the `.env` file.
- To use the `env-package.js` file:
Create the npm script `env:package` command.
Add the `env:package` command to the `dev`, `build`, `start` and `generate` commands.
- In the `env` section of the `nuxt.config.js` file:
Create the `repoName` and `repoDescription` variables with the value `process.env.PACKAGE_NAME` and `process.env.PACKAGE_DESCRIPTION`.
The value of these variables will be the value of the ENV variables created with the `env:package` script.
- To print the `process.env.repoName` and `process.env.repoDescription` environment variables:
In the `nuxt.config.js` file, use `head()` instead of `head{}`.
In the `PageHeader` component and `about` page, create the `getRepoName` computed property.
- To fix the `eslint` error about `importAssertions`:
Install the `@babel/plugin-syntax-import-assertions` package.
In the `.babelrc` file add the `"plugins": ["@babel/plugin-syntax-import-assertions"]` line.

References:
- https://www.youtube.com/watch?v=OusmYXqi-aQ